### ISSUE TITLE
Comentarios sobre bugs do programa

### ISSUE THREAD

**Issue by tonyfrance** [aronsales/wumpusgrp4#1]
Área reservada para discussão de bugs.

**Comment by drbeco** [comment]
Marquei esse issue como "inválido" pelo simples fato dele descaracterizar exatamente o que são os issues.

**cada bug é uma entrada nova de issue**

Cada bug deve ter seu issue e sua discussão, e quando for corrigido, deve ser fechado. Senão não fecharia nenhum!

E cada issue tem que estar associado com o milestone de acordo com o tema do seu bug.

Ok? Fechar aqui.
