### ISSUE TITLE
Conferir Milestones

### ISSUE THREAD

**Issue by drbeco** [aronsales/wumpusgrp4#10]
| N | Data | Milestone | Descrição |
| --- | --- | --- | --- |
| 1 | 17/11/15 | Versão 0.1 | Criar repositório, rascunhos, clones, ramos, add autores |
| 2 | 19/11/15 | Versão 0.2 | Fazer um agente funcional mínimo que passeie pelo labirinto |
| 3 | 26/11/15 | Versão 0.3 | Colocar alguma inteligência no agente |
| 4 | 03/12/15 | Versão 0.4 | Melhorar as respostas dadas para as percepções do agente |
| 5 | 10/12/15 | Versão 0.5 | Lembrar dos caminhos, casas seguras, pegar o ouro com sucesso |
| 6 | 17/12/15 | Versão 1.0 | Buscar a saída através de caminho seguro. Versão Final |
| 7 | 20/12/15 | Versão 1.1 | Versão final após adiamento. |

**Comment by drbeco** [comment]
Reaberto. Tony, só fechar quando a tarefa estiver cumprida.

Todos milestones estão com o nome errado. Nome = Versão XXX. O que está como nome deveria estar como parte da descrição.

Além disso, algumas datas estão incorretas. Confira na tabela as datas. Também a quantidade, são 7, só tem 6 criados.

Uma quantidade de erros, não deveria ter fechado o bug sem acertar tudo.

**Comment by aronsales** [comment]
Ajustes feitos, milestones criados e editados, descrições adicionadas.
