### ISSUE TITLE
Versão final após adiamento.

### ISSUE THREAD

**Issue by tonyfrance** [aronsales/wumpusgrp4#11]

**Comment by drbeco** [comment]
Para que serve este issue? Tony, acho que você não está compreendendo o uso da ferramenta.

Ali do lado tem "labels" que você marca o tipo de issue (que é sinônimo de bug).

Cada um criado, deve ter uma descrição. Este que você criou não tem descrição. Sobre o que se trata?

"Versão final após adiamento" é o que?

Trate os issues como TAREFAS IMEDIATAS, cumprindo-as, acrescentando as próximas etapas, e cumprindo-as também. Cada etapa com seu prazo, cada tarefa avançando o código para o melhor código possível até a entrega da versão final.

Então, se esse issue não é nenhum bug e não tem descrição, marque-o como inválido e feche. Caso contrário, inclua uma descrição de um problema específico.

**Comment by drbeco** [comment]
Se tem dúvidas, navegue pelo github e olhe o código de outros programadores pelo mundo!

Veja como funcionam os bugs, como são as discussões, o que se espera desta ferramenta.

Tem que ser cada issue para tratar um problema específico.

Vá na página inicial do github e faça uma busca por algo genérico, por exemplo "game" ou "pacman", etc., procure um repositório bem "cheio" de gente e de issues, e leia como são feitos, do que tratam, para que servem.

**Comment by aronsales** [comment]
Professor, vou arrumar todos os problemas agora, peço desculpas em nome do grupo, irei pesquisar e retorno com informações corretas.

**Comment by aronsales** [comment]
Professor, trataremos de hoje em diante issues como problemas especificos, que podem ser caracterizados por diversas ''labels'',como bugs,help, dentre outros, como o senhor nos advertiu.

**Comment by aronsales** [comment]
Professor, trataremos de hoje em diante issues como problemas especificos, que podem ser caracterizados por diversas ''labels'',como bugs,help, dentre outros, como o senhor nos advertiu.
Peço mais uma vez desculpas em nome do grupo.
