### ISSUE TITLE
Problemas ao colocar uma lista como ação

### ISSUE THREAD

**Issue by aronsales** [aronsales/wumpusgrp4#12]
Ao colocar uma lista como ação, o agente só está repetindo 1x a lista, na próxima percepção que supostamente traria outra lista de movimentos, ele não executa, coloco este issue como help, para que todos do grupo tentem resolver este problema com a maior rapidez possível.

**Comment by drbeco** [comment]
Se você tem uma lista com "N" elementos e tem um comando que diz para executar o "PRIMEIRO" elemento, é isso que vai acontecer sempre: vai executar sempre o primeiro elemento.

**Comment by aronsales** [comment]
Obrigado pela dica professor, iremos modificar a maneira que usamos
