### ISSUE TITLE
frente(Pos0, Angulo, Pos1)

### ISSUE THREAD

**Issue by drbeco** [aronsales/wumpusgrp4#14]
Pessoal, a "sugestão" é compulsória:

Faça um predicado que calcule a posição P1, que é a posição imediatamente na "frente" da posição P0, dados P0 e ângulo.

Por exemplo, seja `P0=[2,1]` onde `Coluna=2` e `Linha=1`:

```
?- frente([2,1], 0, X).        % para direita
X = [3,1]                      %
?- frente([2,1], 90, X).       % para cima
X = [2,2]                      %
?- frente([2,1], 270, X).      % para baixo
X = [2,1]                      % trombou, fica na mesma
?-
```

**Comment by aronsales** [comment]
Professor, coloquei um esboço muito primitivo no código, deixo esse issue aberto para possíveis discussões com meus colegas de grupo.

**Comment by bmhori** [comment]
Aron, corrigi uns erros que você colocou na sua função primitiva. Quando puder olha.  :+1:

**Comment by bmhori** [comment]
``local_agent :-
    orientacao(0),
    posicao(X,Y),
    Z is X + 1,
    X < 4,
    retractall(posicao(_,_)),
    assert(posicao(Z,Y)).

local_agent :-
    orientacao(90),
    posicao(X,Y),
    Z is Y + 1,
    Y < 4,
    retractall(posicao(_,_)),
    assert(posicao(X,Z)).

local_agent :-
    orientacao(180),
    posicao(X,Y),
    Z is X - 1,
    X  >  1,
    retractall(posicao(_,_)),
    assert(posicao(Z,Y)).

local_agent :-
    orientacao(270),
    posicao(X,Y),
    Z is Y - 1,
    Y  >  1,
    retractall(posicao(_,_)),
    assert(posicao(X,Z)).``

Implementei isso, preciso da colaboração para a regra que calcule a casa da "frente".

**Comment by drbeco** [comment]
Já está funcionando, Bruna?

**Comment by aronsales** [comment]
Função criada, `front_of_me`, porém necessita de alguns ajustes!

**Comment by bmhori** [comment]
Não resolvido!
