### ISSUE TITLE
Quantas flechas tenho?

### ISSUE THREAD

**Issue by drbeco** [aronsales/wumpusgrp4#15]
O agente deve ter um fato próprio pra controlar a qtdd de flechas.

Por exemplo, façam o fato dinâmico: `nflechas(X)` que usar `assert` e `retractall` para marcar se tem 1 ou 0 flechas.

**Comment by aronsales** [comment]
Obrigado pela contribuição professor, pegamos todas suas informações e estamos tentando prosseguir com o trabalho.

**Comment by tonyfrance** [comment]
quando colocava pra rodar as vezes mostrava que ele tinha atirado as flechas inumeras vezes.

**Comment by drbeco** [comment]
Tony, abra um prompt do prolog (`$swipl`) e digite:

```
?- assert(flecha(1)).
?- assert(flecha(2)).
?- flecha(X).
```

E veja o que acontece. Depois teste `retractall(flecha(_))`

**Comment by aronsales** [comment]
Um esboço muito inicial foi botado no agente, iremos trabalhar mais encima dele.
