### ISSUE TITLE
Declarar fatos dinâmicos numa única lista

### ISSUE THREAD

**Issue by drbeco** [aronsales/wumpusgrp4#16]
Pessoal, o código:

```
:- dynamic ([sentiburaco/1]).
:- dynamic ([esbarrada/1]).
:- dynamic ([sentiwumpus/1]).
```

está incorreto. Deve-se usar apenas **UM** `dynamic([ aqui, lista, os, fatos])`

Se tem colchetes, é porque já é uma lista. Se é lista, pode ter muitos elementos. Não desse jeito, com um monte de listas com um único fato.

Ok? Corrigir!

**Comment by aronsales** [comment]
Irei corrigir agora professor.
Mais uma vez obrigado pela colaboração
