### ISSUE TITLE
Failed miserably

### ISSUE THREAD

**Issue by drbeco** [aronsales/wumpusgrp4#17]
## Atualização (master/develop)

A mensagem 
`External function run_agent(Percept, No Action) failed miserably!`
agora mostra qual foi a percepção que o agente recebeu que não soube retornar uma ação.

**Comment by tonyfrance** [comment]
com essa atualizaçao o agente grita quando morre?
![image](https://cloud.githubusercontent.com/assets/14056066/11512353/75161b6a-984c-11e5-8343-3be2e6fc3699.png)

**Comment by tonyfrance** [comment]
com essa atualização o agente grita ao morrer?
![image](https://cloud.githubusercontent.com/assets/14056066/11512574/85c5133e-984d-11e5-84c8-52542626926e.png)

**Comment by drbeco** [comment]
Por favor não apague os comentários.

Sobre o agente imprimir na tela uma mensagem "Aaaaah!", isso nada afeta o programa. O programa não se comunica lendo a entrada/saída padrão, e sim a lista de percepções.

E se o agente morreu, mesmo que ele grite, não há mais nada a fazer, pois o jogo terminou.

**Comment by aronsales** [comment]
Não apaguei não professor, como o senhor respondeu o outro issue de Tony, e o titulou como inválido, achei que a questão estava resolvida.

**Comment by drbeco** [comment]
Ok, tá resolvida. Pode deixar fechada.
