### ISSUE TITLE
Posição do :- dynamic

### ISSUE THREAD

**Issue by drbeco** [aronsales/wumpusgrp4#18]
A linha :

`:- dynamic ([sentiburaco/1,esbarrada/1,sentiwumpus/1]).`

Deve estar no início do arquivo, abaixo apenas de `:- load_files`

O token `:-` indica a leitura de módulos, bibliotecas, arquivos, fatos dinâmicos, etc., e deve estar no início do código fote.

**Comment by aronsales** [comment]
Ajuste realizado.
