### ISSUE TITLE
Fato dinâmico declarado como estático

### ISSUE THREAD

**Issue by drbeco** [aronsales/wumpusgrp4#19]
A linha:

`sentiburaco([turnleft,turnleft,goforward,turnright,goforward]).`

(linha 55), bem como `esbarrad`  e `sentiwumpus` são fatos dinâmicos.

Não podem então ser colocados no código diretamente como se fosse estáticos.

Devem ser colocados na memória com um par retractall/assert dentro de `init_agent`.

**Comment by aronsales** [comment]
Ajustes feitos professor. Obrigado pela contribuição!
