### ISSUE TITLE
agente grita ao morrer

### ISSUE THREAD

**Issue by tonyfrance** [aronsales/wumpusgrp4#20]
o agente esta gritando ao morrer, nao era pra ser so o wumpus que gritaria se morresse?

![image](https://cloud.githubusercontent.com/assets/14056066/11512639/cbcb726a-984d-11e5-9f83-4a885e657abc.png)

**Comment by aronsales** [comment]
Tony, eu acho que ele grita quando cai no buraco, e o wumpus também grita quando morre.

**Comment by drbeco** [comment]
Percepção da imagem acima mostra apenas :`[no,yes,no,no,no]`.

O último item é o grito, e está `no`.

Agora falar que esse "Aaaaaaaaaaa!" aí é algo relevante, tenha santa paciência, espero que não seja disso que se trata esse bug.
