### ISSUE TITLE
agente.pl

### ISSUE THREAD

**Issue by drbeco** [aronsales/wumpusgrp4#23]
Pessoal,

Tem um arquivo extra aí no código que não é para existir.

Faça a união do que tiver que aproveitar, e coloque tudo no agente004.pl.

Em seguida apague o `agente.pl` (`git rm agente.pl`).

**Comment by bmhori** [comment]
Boa noite professor, estamos fazendo isso, esse arquivo foi criado após a discussão, bagunçamos muito o "agente004.pl" por isso criamos o agente.pl as devidas alterações estão sendo feitas.

**Comment by aronsales** [comment]
Pronto professor, fiz a junção dos agentes, tudo ok.

**Comment by drbeco** [comment]
Ok! A questão é conseguir se organizar no github fazendo alterações no código e mantendo histórico (cada commit faz isso). Se for para bagunçar fazendo outros arquivos para tentar se organizar de forma **manual** não é preciso de git / github
