### ISSUE TITLE
retractall(posicao(,)),

### ISSUE THREAD

**Issue by drbeco** [aronsales/wumpusgrp4#26]
No predicado `init_agent`, está errada essa linha (do assunto deste issue).
Um doce para quem apontar e corrigir o erro.

**Comment by aronsales** [comment]
Era pra estar retractall(posicao(_)), e não como estava no código, correto ?
Tentativa de concerto no git

**Comment by drbeco** [comment]
Não exatamente. Cada `_` (chamado de variável anônima) serve para uma variável.

(Português: conSerto)

**Comment by aronsales** [comment]
Também relatei um erro na orientacao, estava escrita diferente no começo da função.

**Comment by drbeco** [comment]
O predicado "posicao/2" tem **dois** argumentos.

**Comment by aronsales** [comment]
No caso retractall(posicao((variavelanonima),(variavelanonima))), ?

**Comment by drbeco** [comment]
Não pergunte para mim, pergunte para o prompt do PROLOG:

```
?- assert(posicao(1,2)).
true.

?- posicao(X,Y).
X = 1, Y = 2 .
```

Aí faça o `retractall...` que você acredita ser certo. E então peça a posição. Deve dar **false**:

```
?- retractall(posicao %... faça aqui como deve ser
true.

?- posicao(X,Y).
false.

?- 
```

Ok?

**Comment by aronsales** [comment]
Correto professor, fiz os testes no prompt, obrigado pela ajuda que o senhor vem dando!

**Comment by bmhori** [comment]
Retractall(posicao(_,_)).

Acho que assim, Aron, pois são dois argumentos.😉

**Comment by drbeco** [comment]
Nao, nao, Bruna. Se for digitar código aqui no **issue**, use a notação do **Markdown** (Veja _Styling with Markdown is supported_)

**Comment by aronsales** [comment]
Foi isso que eu quis dizer bruna, mas não apareceu no issue como era pra ser
retractall(posicao(`_`,`_`))

**Comment by drbeco** [comment]
https://guides.github.com/features/mastering-markdown/

Leia sobre itálico, negrito e principalmente como colocar código:

_itálico_
**negrito**
`código`
