### ISSUE TITLE
Agente inserindo todas as casas como seguras

### ISSUE THREAD

**Issue by aronsales** [aronsales/wumpusgrp4#29]
Ao rodar o agente, o mesmo está direcionando todas as casas como casas seguras, espero a contribuição dos meus colegas para solucionar o problema.

**Comment by bmhori** [comment]
O agente só está salvando as casas da primeira linha como segura, quando ele "sobe", não salva como segura, mesmo ela sendo segura.

**Comment by drbeco** [comment]
Fui ler o código para tentar entender o motivo. O código está atualizado (ramo develop)?

Dá para ser mais específico onde/quando o problema ocorre?

**Comment by aronsales** [comment]
Boa noite professor, tentamos encontrar o problema e acabamos em outros, só as casas [3,1] e [4,1] estão sendo inseridas como seguras.
Já nas casas visitadas, estas só inserem [1,2][1,3][1,4], isto é, só da primeira fileira.
Passamos a noite/madrugada tentando achar o erro que ocasionava isso, mas não achamos, se o senhor puder dar uma dica todo o grupo será bastante grato
Att

**Comment by bmhori** [comment]
Uma observação professor, as casa [3,1] e [4,1] são inseridas como seguras independente de possuírem buraco ou wumpus.

**Comment by drbeco** [comment]
Quais predicados são responsáveis (suspeitos) pelo erro?

**Comment by aronsales** [comment]
Os predicados da posição, pois podem estar dando uma posição errada a função das casas seguras e por isso está dando erro ?

**Comment by aronsales** [comment]
Realmente estavam errados professor, estou trabalhando na correção

**Comment by aronsales** [comment]
Resolvido professor, o agente está inserindo corretamente as casas visitadas e seguras.

**Comment by aronsales** [comment]
Problema resolvido!
