### ISSUE TITLE
Tiro aleatório.

### ISSUE THREAD

**Issue by bmhori** [aronsales/wumpusgrp4#32]
Preciso da colaboração para corrigir o problema da orientação do agente, pois ele sente o wumpus e atira independente da orientação, assim acerta o wumpus apenas alguma vezes.

**Comment by drbeco** [comment]
Bruna,

Esse é um problema complicado, mas aí vai a dica para a solução:

É preciso ter uma lista de casas suspeitas de wumpus. Conforme o agente anda pelo mundo, ele elimina dessa lista as casas que ele deduzir que não tem wumpus quando ele contornar tal casa e não sentir fedor.

Então apenas quando a lista tiver uma única casa o agente deduziu a posição exata do wumpus. Só então ele se dirige para o local, mira e atira.

Como você pode ver, exige bastante avanço no código.

Se vocês ainda estão com dificuldades na navegação do agente, recomendo se concentrar nos problemas mais básicos primeiro. Pode deixar ele atirando aleatório. O prazo é curto para tentar fechar todos os problemas.

Façam um "bom" agente ao invés de "não" fazerem um "ótimo" agente.

**Comment by bmhori** [comment]
Foi implementada uma função de "fuga de emergência".
