### ISSUE TITLE
Atualização do master.

### ISSUE THREAD

**Issue by bmhori** [aronsales/wumpusgrp4#35]
Não estou conseguindo fazer o merge do develop no master, para poder da o push, está dando conflito, usei o "git m3" e não funcionou. 
Algma dica de como resolver isso?

**Comment by drbeco** [comment]
Você usou de forma errada o `git m3` e salvou um arquivo com marcadores de diferença entre arquivos (sinais `<<<<<` e `=====` )

O `git m3` nada mais é que o `vi` com três janelas. A da esquerda, arquivo base; direita, arquivo trazendo o merge; e a do meio deve ficar correta, pois é ela que será o arquivo onde o merge é feito, e será salva como `agente004.pl`

Então, quando estiver editando o conflito, siga as dicas do texto no dropbox e salve a janela do meio do jeito que deve ficar o código.

**Comment by drbeco** [comment]
Eu fiz um push e coloquei o `master` novamente como estava com a tag v1.0

Refaça o merge com o `develop`, preste atenção no código como você quer que fique se der conflito. Se não der conflito, após o merge e antes de fazer commit e push, abra o código com o vi e confira tudo.

**Comment by drbeco** [comment]
Refresque minha memória: seu código está mais organizado no develop ou no master? Quem tem que atualizar quem?

Estava olhando o develop e ele contém o `;` que comentamos, e o master não tem. Por isso fiquei na dúvida de qual é o código melhor.

**Comment by bmhori** [comment]
Master atualizado! :smile:
