### ISSUE TITLE
Casas seguras e visitadas

### ISSUE THREAD

**Issue by aronsales** [aronsales/wumpusgrp4#36]
O agente está inserindo todas as casas seguras como seguras, gostaria de fazer com que o agente mostrasse as casas seguras que não foram visitadas, para melhor desempenho do código.
Já tentei essa forma - 
`casas_seguras(A),`
`delete(A,[[X,Y]],S),` **Onde [X,Y] é a casa atual, e por isso, visitada**
`assert(casas_seguras(S)).`

**Comment by drbeco** [comment]
![image](https://cloud.githubusercontent.com/assets/5805111/11911686/b7507b20-a5fc-11e5-8f45-5f025dab35ec.png)

**Comment by bmhori** [comment]
Não entendi, Professor.

**Comment by aronsales** [comment]
Professor, me desculpe mas eu também não entendi :disappointed:

**Comment by drbeco** [comment]
Tentando de novo:

![image](https://cloud.githubusercontent.com/assets/5805111/11911821/7f0ea476-a601-11e5-8824-0a1f004fd789.png)

**Comment by drbeco** [comment]
Além desse erro, ainda tem esse:

![image](https://cloud.githubusercontent.com/assets/5805111/11911824/cdbe4f0e-a601-11e5-9aa8-fb1feb7813ce.png)

**Comment by aronsales** [comment]
Funcionou professor ! 
O que estava faltando era o retractall, e retirar os parenteses do delete
`retire:-`
`casas_seguras(A),`
`posicao([X,Y]),`
`delete(A,[X,Y],C),`
`retractall(casas_seguras(_)),`
`assert(casas_seguras(C)).`
Obrigado mais uma vez professor !

**Comment by drbeco** [comment]
Tem que aprender a usar o _prompt_ do PROLOG a seu favor. Quando tiver uma ideia, coloque-a para teste. Não é preciso escrever código em arquivo e rodar com `swipl -s arquivo`. Basta abrir o `swipl` e rodar diretamente.
