### ISSUE TITLE
Casas perigosas inserindo visitadas

### ISSUE THREAD

**Issue by aronsales** [aronsales/wumpusgrp4#37]
A função casas perigosas está inserindo também as casas ''perigosas'' que já foram visitadas, o caminho deverá ser o mesmo da função `retirar_seguras`, se algum colega estiver disposto a contribuir serei grato!

**Comment by bmhori** [comment]
Podemos tentar fazer uma intersecção dessas listas.

**Comment by bmhori** [comment]
Não resolvido!
