### ISSUE TITLE
Agente não sobe.

### ISSUE THREAD

**Issue by bmhori** [aronsales/wumpusgrp4#38]
Preciso de ajuda o mais rápido possível para fazer o agente percorrer todo o mapa.

**Comment by aronsales** [comment]
O que estava acontecendo é que a função `local_agent` estava retornando falso quando a posição era [1,1], coloquei mais 4 clausulas na função, onde independente da orientação, o agente insere a própria casa como posição, fazendo com que a função retorne `true`,e o agente ande para frente, trombe, e rode.
