### ISSUE TITLE
Sentir as percepções 

### ISSUE THREAD

**Issue by tonyfrance** [aronsales/wumpusgrp4#4]
Nesta altura, se mover de acordo com as percepções, como evitar brisas e fedores.

**Comment by drbeco** [comment]
Isso que você está fazendo de relatar as etapas o milestone já faz.

BUG INVÁLIDO.

Crie um bug com problemas específicos que você encontrou ao TENTAR EVITAR BRISAS. Crie outro conforme o comportamento do agente se mostra errado (bug) ao tentar evitar fedores. Etc.
