### ISSUE TITLE
Rota de bsuca

### ISSUE THREAD

**Issue by tonyfrance** [aronsales/wumpusgrp4#5]
Estamos quase no final do programa quando chegarmos nessa parte,aqui sera onde aperfeiçoaremos a logica do programa, prioridades, a inteligencia do agente004.

**Comment by drbeco** [comment]
Inválido. Não traz discussões sobre tarefas/problemas/bugs específicos. Discutir o avanço do código e os problemas específicos relacionados à inteligência do agente por exemplo.
