### ISSUE TITLE
Atividade?

### ISSUE THREAD

**Issue by drbeco** [aronsales/wumpusgrp4#9]
**ATENÇÃO!! MENSAGEM IMPORTANTE!! ATENÇÃO!!**

-Antonio Francelino
-Aron Sales Monteiro
-Bruna Mayumi Hori
-Thiago Rodrigo de Oliveira Queiroz

---

Caros alunos, o fato de algum de vocês estarem inativos e não terem preocupação maior com a disciplina não significa que não possam ter a especial gentileza de ajudarem os colegas. Então faço a seguinte **consideração**:

Quem ainda está ativo deve permanecer neste grupo 4. Os inativos serão transferidos para o grupo 5.

1- Este issue, obviamente, é para ser respondido apenas por quem ainda tem interesse.
2- Quem tem interesse, deve se mostrar ativo, ter boa participação, responder aos bugs com celeridade, e por isso, como este aqui É UM ISSUE (bug), a sua resposta deve ser rápida também.

Dito isso, vou considerar este grupo:
- INATIVO se ninguém responder até amanhã.
- ATIVO se todos responderem (neste caso não há necessidade de mesclar com o grupo 5 e vocês continuam o trabalho aqui no grupo 4.)
- DIVIDIDO: se alguns responderem e outros não, até o prazo de amanhã (terça, 24/11/15), meia noite, então os que estão ativos permanecerão no grupo 4. Os inativos serão transferidos para o grupo 5. O mesmo eu perguntarei no grupo 5, e os ativos de lá passarão para cá.

**ATENÇÃO!! MENSAGEM IMPORTANTE!! ATENÇÃO!!**

**Comment by aronsales** [comment]
Ativo professor, não tive tempo de mecher no wumpus em si este final de semana, mas já dei uma adiantada boa tirando dúvidas com Paulo(monitor de lógica) e estudando sobre listas, conjuntos e intersecções.

**Comment by bmhori** [comment]
Ativa professor, estou estudando melhor o assunto para poder alterar, como Aron estou tirando dúvidas com o monitor antes de começar a editar o programa.

**Comment by tonyfrance** [comment]
ativo, esse final de semana nao pude fazer nada por motivos pessoais, mas estou estudando, tirando duvidas e discutindo com meus colegas sobre o programa.

**Comment by thiagooqueiroz** [comment]
Ativo professor, estou estudando alguns assuntos, tirando duvidas com o monitor e padrinho ,para poder editar o programa.

**Comment by drbeco** [comment]
Ok! Grupo ativo. Talvez vcs recebam algum integrante do grupo 5 se ele não estiver totalmente ativo. Quarta-feira vemos isso. Fechando aqui. Bons estudos.

**Comment by tonyfrance** [comment]
obrigado
